import { Router } from 'express'
import { catchAsync } from '../middleware/'
import { validate, registerSchema } from '../validation'
import { User } from '../models'
import { BadRequest } from '../errors'
import { logIn } from '../services'
